#!/bin/bash
#   BAREOS® - Backup Archiving REcovery Open Sourced
#
#   Copyright (C) 2025 Bareos GmbH & Co. KG
#
#   This program is Free Software; you can redistribute it and/or
#   modify it under the terms of version three of the GNU Affero General Public
#   License as published by the Free Software Foundation and included
#   in the file LICENSE.
#
#   This program is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
#   02110-1301, USA.

set -e
set -o pipefail
set -u

#
# Requirements:
# * This tests is implemented for a OmniOS NDMP storage.
# * To create and delete backup data,
#   password-less SSH root access to the Omnios storage is required.
# * run cmake with parameter matching your environment:
#     -Dndmp_data_agent_address=<ip.of.data.agent> \
#     -Dndmp_data_agent_user=<user> \
#     -Dndmp_data_agent_password=<password>
#

TestName="$(basename "$(pwd)")"
export TestName

#shellcheck source=../environment.in
. ./environment

if [ -f ./environment.local ]; then
  . ./environment.local
fi

#shellcheck source=../scripts/functions
. "${rscripts}"/functions
"${rscripts}"/cleanup
"${rscripts}"/setup

start_test

start_bareos

BCONSOLE=bin/bconsole
STARTJOBID=1
NDMPCLIENT=omnios

${BCONSOLE} <<< "status client=ndmp-fd
status director
status storage=ndmpfile
"

cleanup_remote

echo "################ running NDMP failing first full to trigger rerun #####################"

${BCONSOLE} <<< "run job=NDMPBackupDump fileset=${NDMPCLIENT}-fileset level=Full yes"
check_jobid_failed $((STARTJOBID))

# Create data so rescheduled job will work
make_data_remote
sleep 60

# Once fixed use check_jobid instead
# ``Fatal error: No backup type specified in NDMP job``
check_jobid_failed $((STARTJOBID))

# To be fixed storage should not wait anymore the FD connection.
# With client passive = yes, this is working immediately.
# but not always ...
#status storage=ndmpfile
#Job inventory:
#
#Backup Job omniosdump.2025-08-18_14.06.34_05 waiting for Client connection.
#JobId=1 Level=Full Type=Backup Name=omniosdump Status=Waiting on FD
#Writing: Volume="isilon-0001"
#    pool="isilon" device="FileStorage" (storage)
#    spooling=0 despooling=0 despool_wait=0
#    Files=0 Bytes=0 AveBytes/sec=0 LastBytes/sec=0
#    FDSocket closed
#
#====
#
#Jobs waiting to reserve a drive:
#====
#
#Terminated Jobs:
# JobId  Level    Files      Bytes   Status   Finished        Name
#===================================================================
#     1  Full          1       112   Cancel   18-Aug-25 14:06 omniosdump
#

status_storage=$(${BCONSOLE} <<< "status storage=ndmpfile")
if grep 'Status=Waiting on FD' <<< "${status_storage}"; then
  set_error "${RESULT}"
  exit 1
fi

# At that point the storage has release the resource
echo "################ rerun manually NDMP backup full #####################"

### Fix the failing job
$BCONSOLE <<< "rerun jobid=${STARTJOBID} yes"
STARTJOBID=$((STARTJOBID+1))
check_jobid $((STARTJOBID))

# Jobid 2 might failed if restarted while the Storage is still waiting on previous FD
# If all jobs are canceled we might have this issue at the end of jobid 2
# bareos-dir JobId 2: Fatal error: NumConcurrentJobs Dec Wstore=LocalfileStorage wncj=-1


echo "################ running NDMP backup incrementals #####################"
${SSH} dd if=/dev/zero of=/${mountpoint}/home/regress/${NDMP_FILESYSTEM}/incremental bs=1M count=2

for ID in $(seq 1 10); do
  ${SSH} "echo ${NDMP_FILESYSTEM}-${ID} >> /${mountpoint}/home/regress/${NDMP_FILESYSTEM}/incremental"
  ${BCONSOLE} <<< "run job=NDMPBackupDump fileset=${NDMPCLIENT}-fileset level=Incremental yes"
  check_jobid $((STARTJOBID+${ID}))
done

# restore

# remove files
cleanup_remote

echo "################ restore single file #####################"
# restore  single file
${BCONSOLE} <<< "restore jobid=$((STARTJOBID)) client=ndmp-fd fileset=${NDMP_CLIENT}-fileset restorejob=NDMPRestoreDump select yes
mark /${mountpoint}/home/regress/${NDMP_FILESYSTEM}/testfile
done
wait
"
((ID++))
check_jobid $((STARTJOBID+${ID}))

${SSH} "cat /${mountpoint}/home/regress/${NDMP_FILESYSTEM}/testfile" | diff - sbin/bareos_dir-ndmp-bareos

# remove files
cleanup_remote


echo "################ restore full #####################"
# restore full
${BCONSOLE} <<< "restore jobid=$((STARTJOBID)) client=ndmp-fd fileset=${NDMP_CLIENT}-fileset restorejob=NDMPRestoreDump all done yes"
((ID++))
check_jobid $((STARTJOBID+${ID}))

${SSH} "tail -c 200 /${mountpoint}/home/regress/${NDMP_FILESYSTEM}/full | grep ${NDMP_FILESYSTEM}"

# remove files
cleanup_remote

echo "################ restore full to different RELATIVE location /prefix #####################"
# restore full to different RELATIVE location "/prefix"
${BCONSOLE} <<< "restore jobid=$((STARTJOBID)) client=ndmp-fd fileset=${NDMP_CLIENT}-fileset restorejob=NDMPRestoreDump where=/bareos-restores-${NDMP_FILESYSTEM} all done yes"
((ID++))
check_jobid $((STARTJOBID+${ID}))

# Shouldn't that failed ?
${SSH} "tail -c 200 /${mountpoint}/home/regress/${NDMP_FILESYSTEM}/full | grep ${NDMP_FILESYSTEM}"
# and this one working ?
#${SSH} "tail -c 200 /${mountpoint}/home/regress/${NDMP_FILESYSTEM}/bareos-restores-${NDMP_FILESYSTEM}/full | grep ${NDMP_FILESYSTEM}"

# remove files
cleanup_remote

echo "################ restore full to different ABSOLUTE location ^/prefix #####################"
# restore full to different ABSOLUTE location "^/prefix"
${BCONSOLE} <<< "restore jobid=$((STARTJOBID)) client=ndmp-fd fileset=${NDMP_CLIENT}-fileset restorejob=NDMPRestoreDump where=^/${mountpoint}/data/bareos-restores-${NDMP_FILESYSTEM} all done yes"
((ID++))
check_jobid $((STARTJOBID+${ID}))

${SSH} "tail -c 200 /${mountpoint}/home/regress/${NDMP_FILESYSTEM}/full | grep ${NDMP_FILESYSTEM}"

#${SSH} "tail -c 200 /${mountpoint}/data/bareos-restores-${NDMP_FILESYSTEM}/full | grep ${NDMP_FILESYSTEM}"

# remove files
cleanup_remote

echo "################ restore incremental #####################"
# restore incremental
${BCONSOLE} <<< "restore jobid=$((STARTJOBID+1)) client=ndmp-fd fileset=${NDMP_CLIENT}-fileset restorejob=NDMPRestoreDump select current
mark /${mountpoint}/home/regress/${NDMP_FILESYSTEM}/incremental
done
yes
"
((ID++))
check_jobid $((STARTJOBID+${ID}))

${SSH} "tail -c 200 /${mount_point}/home/regress/${NDMP_FILESYSTEM}/incremental | grep ${NDMP_FILESYSTEM}-1"

# cleanup
cleanup_remote

exit 0

echo "################ run copy job #####################"
# run copy job
${BCONSOLE} <<< "run job=ndmp-copy-$NDMPCLIENT yes
wait
messages
"
echo "################ restore copy of full job #####################"

# restore copy
ID=18
${BCONSOLE} <<< restore jobid=$((STARTJOBID+${ID})) client=ndmp-fd fileset=${NDMP_CLIENT}-fileset restorejob=NDMPRestoreDump all done yes
wait
messages
${SSH} "tail -c 200 /${mount_point}/home/regress/${NDMP_FILESYSTEM}/full | grep ${NDMP_FILESYSTEM}"
#${SSH} "grep ${NDMP_FILESYSTEM} /${mount_point}/home/regress/${NDMP_FILESYSTEM}/full"

cleanup_remote

ID=28
echo "################ restore copy of incremental job #####################"
# restore copy of incremental
${BCONSOLE} <<< "restore jobid=$((STARTJOBID+${ID})) client=ndmp-fd fileset=${NDMP_CLIENT}-fileset restorejob=NDMPRestoreDump all done yes
wait
messages
"
${SSH} "tail -c 200 /${mount_point}/home/regress/${NDMP_FILESYSTEM}/incremental | grep ${NDMP_FILESYSTEM}"

# final cleanup
cleanup_remote

check_for_zombie_jobs storage=ndmpfile client=ndmp-fd

end_test
