#!/bin/bash

#   BAREOS® - Backup Archiving REcovery Open Sourced
#
#   Copyright (C) 2024-2025 Bareos GmbH & Co. KG
#
#   This program is Free Software; you can redistribute it and/or
#   modify it under the terms of version three of the GNU Affero General Public
#   License as published by the Free Software Foundation and included
#   in the file LICENSE.
#
#   This program is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
#   02110-1301, USA.

set -e
set -o pipefail
set -u

#
# run config test (-t) for each daemon with defaultconfig files
#

TestName="$(basename "$(pwd)")"
export TestName

#shellcheck source=../environment.in
. ./environment

#shellcheck source=../scripts/functions
. "${rscripts}"/functions

"${rscripts}"/cleanup
"${rscripts}"/setup

start_test()
{
  # in case of an exit during the test,
  # call the 'end_test' function.
  trap '
         EXITCODE=$?;
         echo "exit($EXITCODE) is called. Set test to failure and end test.";
         estat=998;
         end_test;
      ' EXIT
  check_encoding
  STARTDATE="$(date +%R:%S)"
  echo " "
  echo " "
  echo "=== $TestName: starting at $STARTDATE ==="
  echo "=== $TestName: starting at $STARTDATE ===" >>"${working}/log"
  echo "="
  echo "="
  export TestName
  export zstat
  export estat
  estat=0
  zstat=0
  bstat=0
  rstat=0
  dstat=0
  # marker for cleanup()
  echo "$STARTDATE" >"${working}/CLEANUPMARKER"
#  bin/bareos status || true
}


start_test

BAREOS_CONFIG_DIR="$(pwd)/etc/bareos"
os_type=$(uname -s)
if [ "$os_type" = "Darwin" ] || [ "$os_type" = "FreeBSD" ]; then
  SED="sed -i ''"
else
  SED="sed --in-place"
  if [ "$os_type" = "Windows" ]; then
    conf=$(cygpath -w "${BAREOS_CONFIG_DIR}")
  fi
fi

echo " ====== env ===== "
env

# bareos-fd
echo -n "Testing bareos-fd    :"
# fix working non existing default working dir
${SED} "s,\(Name.*=.*-fd\).*$,\1\n  Working Directory = \"$(pwd)/working\"\n,g" "${BAREOS_CONFIG_DIR}/bareos-fd.d/client/myself.conf"
if ! "${BAREOS_FILEDAEMON_BINARY}" --verbose --config "${conf}" --test-config; then
  set_error "bareos-fd default configuration failed"
  exit 1
fi
echo " OK"

#bareos-sd
echo -n "Testing bareos-sd    :"
# fix working non existing default working dir
${SED} "s,\(Name.*=.*-sd\).*$,\1\n  Working Directory = \"$(pwd)/working\"\n,g" "${BAREOS_CONFIG_DIR}/bareos-sd.d/storage/bareos-sd.conf"
# adjust sd_backenddir
${SED} "s,\(Name.*=.*-sd\).*$,\1\n  Backend Directory = \"${sd_backenddir}\"\n,g" "${BAREOS_CONFIG_DIR}/bareos-sd.d/storage/bareos-sd.conf"
# adjust default device storage location
${SED} "s,\(Archive.*Device.*=\)\(.*\)$,\1 \"storage/\"\n,g" "${BAREOS_CONFIG_DIR}/bareos-sd.d/device/FileStorage.conf"
if ! "${BAREOS_STORAGEDAEMON_BINARY}" --verbose --config "${conf}" --test-config; then
  set_error "bareos-sd default config failed"
  exit 2
fi
echo " OK"

#bareos-dir
echo -n "Testing bareos-dir   :"
# fix working non existing default working dir
${SED} "s,\(Name.*=.*-dir\).*$,\1\n  Working Directory = \"$(pwd)/working\"\n,g" "${BAREOS_CONFIG_DIR}/bareos-dir.d/director/bareos-dir.conf"
if ! "${BAREOS_DIRECTOR_BINARY}" --verbose --config "${conf}" --test-config; then
  set_error "bareos-dir defaultconfig failed"
  exit 3
fi
echo " OK"

#bconsole
echo -n "Testing bconsole     :"
if ! "${BAREOS_BCONSOLE_BINARY}" --config "${conf}" --test-config; then
  set_error "bareos bconsole defaultconfig failed"
  exit 4
fi
echo " OK"

# tray-monitor
if [ -n "${BAREOS_TRAY_MONITOR_BINARY=-}" ] && [ "$BAREOS_TRAY_MONITOR_BINARY" != './/' ]; then
  echo -n "Testing tray-monitor :"
  if ! QT_QPA_PLATFORM=offscreen "${BAREOS_TRAY_MONITOR_BINARY}" --config "${conf}" --test-config; then
    set_error "bareos bconsole defaultconfig failed"
    exit 5
  fi
  echo " OK"
else
  echo    "Testing tray-monitor : Skipped"
fi

end_test
