#!/bin/bash

#   BAREOS® - Backup Archiving REcovery Open Sourced
#
#   Copyright (C) 2025-2025 Bareos GmbH & Co. KG
#
#   This program is Free Software; you can redistribute it and/or
#   modify it under the terms of version three of the GNU Affero General Public
#   License as published by the Free Software Foundation and included
#   in the file LICENSE.
#
#   This program is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
#   02110-1301, USA.

# This testrunner performs a restore after eject the volume containing the jobid

set -e
set -o pipefail
set -u

TestName="$(basename "$(pwd)")"
export TestName

#shellcheck source=../../environment.in
. ./environment
#shellcheck source=test-config.in
. ./test-config

#shellcheck source=../../scripts/functions
. "${BAREOS_SCRIPTS_DIR}"/functions

start_test

on_error()
{
  local lc="${BASH_COMMAND}"
  echo "Error occurred in testrunner script [${lc}]"
  export estat=1
  exit 1
}
trap 'on_error' ERR

jobid_to_restore=$(head -n 1 ${tmp}/list_of_jobids)

#determine volume to eject
volume_to_eject=$(bconsole <<< ".api 2
list volumes jobid=${jobid_to_restore}
" | awk -F " " '/^.*"volumename":/ {gsub("\"","",$2);gsub(" ","",$2);gsub(",","",$2);print $2}'
)

cat <<END_OF_DATA >"${tmp}/bconcmds"
@$out ${log_home}/eject_volume_to_restore.out
export volume=${volume_to_eject} storage=Tape-0
wait
list volume=${volume_to_eject}
quit
END_OF_DATA

run_bconsole

# Add check for slot=0?

echo "Set debug on the Tape-Storage daemon"
tracefile="$(echo "setdebug level=200 trace=1 storage=Tape-0" | bin/bconsole | grep "^3000" | awk -F"tracefile=" '{print $2}')"
: >"${tracefile}" # clear tracefile

echo "Run restore"

cat <<END_OF_DATA >"${tmp}/bconcmds"
@$out ${log_home}/restore_non_present_volume.out
restore jobid=${jobid_to_restore} where=${tmp}/bareos_restores_novolume select all done yes
messages
quit
END_OF_DATA

run_bconsole

# What we want to found in the log
expect_grep "No slot defined in catalog (slot=0)" \
	"${log_home}/restore_non_present_volume.out" \
	"no no slot defined found in log"

expect_grep "Cartridge change or \"update slots\" may be required." \
	"${log_home}/restore_non_present_volume.out" \
	"no cartridge change message found in log"

expect_grep "Please mount read Volume \"${volume_to_eject}\" for:" \
	"${log_home}/restore_non_present_volume.out" \
	"no please mount volume message found in log"

if [ ${estat} -ne 0 ]; then
  exit ${estat}
fi

# What we absolutely not want to see in the log
expect_not_grep "Error: stored/block.cc:1004 Read error on fd=8" \
	"${log_home}/restore_non_present_volume.out" \
	"stored/block.cc errors found in log"

expect_not_grep "Warning: stored/acquire.cc:317 Read acquire:" \
	"${log_home}/restore_non_present_volume.out" \
	"stored/acquire.cc errors found in log"

if [ ${estat} -ne 0 ]; then
  exit ${estat}
fi

#cancel running jobs

cat <<END_OF_DATA >"${tmp}/bconcmds"
@$out ${log_home}/cancel_all.out
cancel all yes
wait
messages
quit
END_OF_DATA

run_bconsole

end_test
exit 0
