#!/bin/bash
#   BAREOS® - Backup Archiving REcovery Open Sourced
#
#   Copyright (C) 2019-2024 Bareos GmbH & Co. KG
#
#   This program is Free Software; you can redistribute it and/or
#   modify it under the terms of version three of the GNU Affero General Public
#   License as published by the Free Software Foundation and included
#   in the file LICENSE.
#
#   This program is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
#   02110-1301, USA.

# This test will execute a first local copy from pool=Full to pool=Copy
set -e
set -o pipefail
set -u

TestName=02-copy

#shellcheck source=../environment.in
. ./environment

#shellcheck source=../scripts/functions
. "${rscripts}"/functions

copy_log="$tmp/copy_log.out"
query_results="$tmp/query_results.out"

start_test

cat <<END_OF_DATA >"$tmp/bconcmds"
@$out /dev/null
messages
@$out $copy_log
label volume=Copy-0001 storage=Copy pool=Copy
run job=copy yes
wait
messages
@$out $query_results
sqlquery
SELECT type FROM job WHERE jobid=5;
.
quit
END_OF_DATA

run_bconsole "$tmp/bconcmds"

expect_grep "Termination:.*Copying OK" \
            "$copy_log" \
            "Copy job did not finish well."

# Update last volume to Used so it will pick by copy volumes
for V in $(bin/bconsole <<< ".api 1
list volumes pool=Copy
" | awk -F "|" '/Append/ {gsub(" ","",$2); print $2}');do
bin/bconsole <<< "update volume=${V} volstatus=Used"
done


end_test
