#!/bin/bash
set -e
set -o pipefail
set -u
#
# This systemtest tests the python-fd contrib plugin
# bareos_mariadb_dump
#
TestName="$(basename "$(pwd)")"
export TestName

#shellcheck source=../environment.in
. ./environment

JobName=backup-bareos-fd
test_db_name="${db_name}_test"
RESTORE_DIR="$tmp/bareos-restores/@mariadbbackup@/"

#shellcheck source=../scripts/functions
. "${rscripts}"/functions
skip_if_root

#shellcheck source=../scripts/mysql.sh
. "${rscripts}"/mariadb.sh
# "${rscripts}"/cleanup
# "${rscripts}"/setup

mariadb_init
mariadb_server_start

echo "create database ${test_db_name}" | ${MARIADB_CLIENT}
echo "CREATE TABLE test ( id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, data VARCHAR(100), created TIMESTAMP DEFAULT NOW())  " | ${MARIADB_CLIENT} "${test_db_name}"
echo "insert into test (data) VALUES ('test entry 1') " | ${MARIADB_CLIENT} "${test_db_name}"

start_test

cat <<END_OF_DATA >${tmp}/bconcmds
@$out ${NULL_DEV}
messages
@$out ${tmp}/log1.out
setdebug level=500 trace=1 timestamp=1 client=bareos-fd
run job=${JobName} yes
wait
setdebug level=0 client=bareos-fd
status director
status client
status storage=File
wait
messages
llist jobs job=$JobName
END_OF_DATA

run_bconsole
expect_grep "Backup OK" "${tmp}/log1.out" "Full Backup not found!"

# insert data and run incremental
echo "insert into test (data) VALUES ('test entry 2') " | ${MARIADB_CLIENT} "${test_db_name}"

cat <<END_OF_DATA2>${tmp}/bconcmds
@$out ${NULL_DEV}
messages
@$out ${tmp}/log2.out
setdebug level=500 trace=1 timestamp=1 client=bareos-fd
run job=${JobName} Level=Incremental yes
wait
setdebug level=0 client=bareos-fd
messages
llist jobs job=$JobName
END_OF_DATA2

run_bconsole
expect_grep "Backup OK" "${tmp}/log2.out" "Incremental Backup not found!"

# run incremental again without any new data
cat <<END_OF_DATA3 >"$tmp/bconcmds"
@$out ${tmp}/log3.out
setdebug level=500 trace=1 timestamp=1 client=bareos-fd
run job=${JobName} yes
wait
setdebug level=0 client=bareos-fd
status dir
llist jobs job=$JobName
END_OF_DATA3

run_bconsole
expect_grep "Backup OK" "${tmp}/log3.out" "Empty Incremental Backup not found!"


cat <<END_OF_DATA4 >"${tmp}/bconcmds"
@$out ${tmp}/log4.out
setdebug level=500 trace=1 timestamp=1 client=bareos-fd
restore restorejob=RestoreFile client=bareos-fd fileset=bareos_mariadb_dump yes select all done
wait
setdebug level=0 client=bareos-fd
status dir
llist jobs job=RestoreFile
END_OF_DATA4

run_bconsole
expect_grep "Restore OK" "${tmp}/log4.out" "Restore OK not found!"


# Check if some files are restored
ls -lR "${RESTORE_DIR}"
if [ -z "$(ls -A "${RESTORE_DIR}")" ]; then
       echo "No restore data found"
       estat=1
fi

check_for_zombie_jobs storage=File
stop_bareos

# delete database
${MARIADB_CLIENT} <<< "DROP DATABASE ${test_db_name};"

if ${MARIADB_CLIENT} "${test_db_name}" <<< "SELECT * FROM test WHERE id=2;" 2>/dev/null; then
    echo "database ${test_db_name} should be deleted and command should fail."
    estat=2
fi

# restore db
${MARIADB_CLIENT} < "${RESTORE_DIR}/${test_db_name}.sql"

if ! ${MARIADB_CLIENT} "${test_db_name}" <<< "SELECT * FROM test WHERE id=2;" >/dev/null; then
    echo "test entry not found after restore"
    estat=3
fi

mariadb_server_stop

end_test
