#!/bin/bash

#   BAREOS® - Backup Archiving REcovery Open Sourced
#
#   Copyright (C) 2024-2025 Bareos GmbH & Co. KG
#
#   This program is Free Software; you can redistribute it and/or
#   modify it under the terms of version three of the GNU Affero General Public
#   License as published by the Free Software Foundation and included
#   in the file LICENSE.
#
#   This program is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
#   02110-1301, USA.

# This systemtest create job record with 1,2 file but 0 bytes
# Consolidation in that case was failing with 
# 
# Version: 24.0.3~pre0.54685a85d (27 March 2025) Ubuntu 22.04.5 LTS
#bareos-dir JobId 103069: Start Virtual Backup JobId 103069, Job=sch-hp-desktop-Users-Pictures.2025-04-16_08.52.03_37
#bareos-dir JobId 103069: Unable to get Job record. ERR=cats/sql_get.cc:267 No Job found for JobName ''
#bareos-dir JobId 103069: No files found to read. No bootstrap file written.
#bareos-dir JobId 103069: Fatal error: Could not create bootstrap file
#bareos-dir JobId 103069: Replicating deleted files from jobids 101984,102016,102055,102099 to jobid 103069
#bareos-dir JobId 103069: Error: Bareos myth-dir 24.0.3~pre0.54685a85d (27Mar25):
#102908 | sch-hp-desktop-Users-Pictures | sch-hp-desktop-fd | 2025-03-22 01:51:07 | 00:01:10 | B | F | 42,740 | 384,907,132,555 | T |
#101984 | sch-hp-desktop-Users-Pictures | sch-hp-desktop-fd | 2025-03-23 02:41:40 | 00:01:07 | B | I | 1 | 0 | T |
#102016 | sch-hp-desktop-Users-Pictures | sch-hp-desktop-fd | 2025-03-24 02:52:38 | 00:01:10 | B | I | 1 | 0 | T |
#102055 | sch-hp-desktop-Users-Pictures | sch-hp-desktop-fd | 2025-03-25 01:13:22 | 00:01:12 | B | I | 1 | 0 | T |
#102099 | sch-hp-desktop-Users-Pictures | sch-hp-desktop-fd | 2025-03-26 01:17:20 | 00:01:08 | B | I | 1 | 0 | T |
#102144 | sch-hp-desktop-Users-Pictures | sch-hp-desktop-fd | 2025-03-27 01:17:23 | 00:01:15 | B | I | 1 | 0 | T |
#102185 | sch-hp-desktop-Users-Pictures | sch-hp-desktop-fd | 2025-03-28 01:50:46 | 00:01:12 | B | I | 1 | 0 | T |
#102222 | sch-hp-desktop-Users-Pictures | sch-hp-desktop-fd | 2025-03-29 02:40:21 | 00:01:13 | B | I | 2 | 0 | T |
#102355 | sch-hp-desktop-Users-Pictures | sch-hp-desktop-fd | 2025-03-30 11:34:40 | 00:01:12 | B | I | 2 | 0 | T |
#102428 | sch-hp-desktop-Users-Pictures | sch-hp-desktop-fd | 2025-04-01 02:41:19 | 00:01:07 | B | I | 3 | 150 | T |
#102474 | sch-hp-desktop-Users-Pictures | sch-hp-desktop-fd | 2025-04-02 01:13:24 | 00:01:08 | B | I | 2 | 0 | T |
#102517 | sch-hp-desktop-Users-Pictures | sch-hp-desktop-fd | 2025-04-03 01:17:33 | 00:01:08 | B | I | 2 | 0 | T |
#102559 | sch-hp-desktop-Users-Pictures | sch-hp-desktop-fd | 2025-04-04 01:17:36 | 00:01:09 | B | I | 2 | 0 | T |
#102603 | sch-hp-desktop-Users-Pictures | sch-hp-desktop-fd | 2025-04-05 01:50:46 | 00:01:07 | B | I | 2 | 0 | T |
#102645 | sch-hp-desktop-Users-Pictures | sch-hp-desktop-fd | 2025-04-06 01:50:49 | 00:01:31 | B | I | 2 | 0 | T |
#102682 | sch-hp-desktop-Users-Pictures | sch-hp-desktop-fd | 2025-04-07 02:41:22 | 00:01:09 | B | I | 2 | 0 | T |
#102723 | sch-hp-desktop-Users-Pictures | sch-hp-desktop-fd | 2025-04-08 02:39:28 | 00:01:03 | B | I | 3 | 150 | T |
#102766 | sch-hp-desktop-Users-Pictures | sch-hp-desktop-fd | 2025-04-09 02:39:37 | 00:01:10 | B | I | 12 | 2,271,549 | T |
#102807 | sch-hp-desktop-Users-Pictures | sch-hp-desktop-fd | 2025-04-10 01:13:21 | 00:01:09 | B | I | 2 | 0 | T |
#102852 | sch-hp-desktop-Users-Pictures | sch-hp-desktop-fd | 2025-04-11 01:17:31 | 00:01:14 | B | I | 2 | 0 | T |
#102888 | sch-hp-desktop-Users-Pictures | sch-hp-desktop-fd | 2025-04-12 01:17:35 | 00:01:25 | B | I | 2 | 0 | T |
#102928 | sch-hp-desktop-Users-Pictures | sch-hp-desktop-fd | 2025-04-13 01:50:45 | 00:01:22 | B | I | 1 | 0 | T |
#102963 | sch-hp-desktop-Users-Pictures | sch-hp-desktop-fd | 2025-04-14 01:50:48 | 00:01:11 | B | I | 2 | 0 | T |
#103002 | sch-hp-desktop-Users-Pictures | sch-hp-desktop-fd | 2025-04-15 02:40:14 | 00:01:18 | B | I | 2 | 0 | T |
#103043 | sch-hp-desktop-Users-Pictures | sch-hp-desktop-fd | 2025-04-16 02:40:17 | 00:01:26 | B | I | 2 | 0 | T |
#
# Original report https://groups.google.com/u/0/g/bareos-users/c/NB4Z3uYGfuU


TestName="$(basename "$(pwd)")"
export TestName

JobName=ai-backup-bareos-fd

#shellcheck source=../environment.in
. ./environment

#shellcheck source=../scripts/functions
. "${rscripts}"/functions
start_test

# Consolidating several zero-file incremental jobs backups

cat <<END_OF_DATA >$tmp/bconcmds
@$out $tmp/extra.log
messages
.api 2
@$out $tmp/zero-file_start.out
@exec "sh -c 'rm -f ${tmp}/data/weird-files/file-4'"
run job=$JobName level=Incremental yes
wait
@exec "sh -c 'rm -f ${tmp}/data/weird-files/file-1'"
run job=$JobName level=Incremental yes
wait
run job=$JobName level=Incremental yes
wait
@$out $tmp/zero-file_consolidate.out
run job=Consolidate yes
wait
@$out $tmp/zero-file_messages.out
.api 1
status director
status client
status storage=File
messages
END_OF_DATA

run_bconsole

# get the second to last jobid (taking into account test restarts)
first_job=$(grep "jobid" "$tmp/zero-file_start.out" | tail -n 3 | head -n 1 | sed 's/["jobid:]//g' | xargs)
second_job=$(grep "jobid" "$tmp/zero-file_start.out" | tail -n 2 | head -n 1 | sed 's/["jobid:]//g' | xargs)
third_job=$(grep "jobid" "$tmp/zero-file_start.out" | tail -n 1 | sed 's/["jobid:]//g' | xargs)
cons_job=$(grep "jobid" "$tmp/zero-file_consolidate.out" | tail -n 1 | sed 's/["jobid:]//g' | xargs)



# this is useful in case this test fails to remove the empty job
# to diagnose the issue
cat <<END_OF_DATA >$tmp/bconcmds
@$out $tmp/empty-files.out
sqlquery
SELECT
  path || name AS path,
  to_timestamp(st_mtime) AS modify,
  to_timestamp(st_atime) AS access,
  to_timestamp(st_ctime) AS change
FROM
  file JOIN path USING (pathid), decode_lstat(lstat)
WHERE
  jobid in (${first_job},${second_job},${third_job});
END_OF_DATA

run_bconsole

expect_grep "purging empty jobids ${empty_job}" \
            "$tmp/zero-file_messages.out" \
            "Removal of expected empty jobs was not successful"

expect_grep "No results to list" \
            "$tmp/empty-files.out" \
            "Somehow the empty job contains files"

expect_grep "purged JobIds .*${first_job} as they were consolidated into Job $((cons_job + 1))" \
            "$tmp/zero-file_messages.out" \
            "consolidation of expected jobs did not happen."
expect_not_grep "purged JobIds .*${empty_job}.* as they were consolidated into Job $((cons_job + 1))" \
		"$tmp/zero-file_messages.out" \
		"consolidation of empty happened."
expect_not_grep "purged JobIds .*${second_job}.* as they were consolidated into Job $((cons_job + 1))" \
		"$tmp/zero-file_messages.out" \
		"consolidation of last incremental happened."

end_test
